### ISSUE TITLE
部分自定义主题不生效

### ISSUE THREAD

**Issue by dream2333** [HelloWuJiaYi/PostToc#1]
一些主题不带目录树，是真的坑

**Comment by dream2333** [comment]
![image](https://github.com/user-attachments/assets/8d89bdc8-5661-4b0f-a48d-5c55c84f628a)
看来有些主题并不能正常显示……
https://www.resourch.com

**Comment by dream2333** [comment]
更改默认的selector可以解决问题，希望可以加入到设置中

**Comment by HelloWuJiaYi** [comment]
已更新，可以适配更多主题
