### ISSUE TITLE
【功能添加】默认位置设置

### ISSUE THREAD

**Issue by irx999** [HelloWuJiaYi/PostToc#6]
您好， 能否添加一个功能 ， 能够设置 该目录出现的默认位置， 我希望能提供一个选项， 比如出现在页面的右上角或右居中
我自己的博客
https://irx999.fun/archives/698/
如图↓
![image](https://github.com/user-attachments/assets/d73cc2a5-ad24-42fb-b2e1-26e58ee37b3e)

**Comment by HelloWuJiaYi** [comment]
1.4.1 已更新，后台可修改默认位置的偏移量。
