### ISSUE TITLE
【bug】卡片内的 标题会重复识别

### ISSUE THREAD

**Issue by irx999** [HelloWuJiaYi/PostToc#8]
{card-describe title="卡片描述"}
#### Dbeaver
一个功能较全的多平台SQL数据库管理软件
 [https://github.com/dbeaver/dbeaver](https://github.com/dbeaver/dbeaver) 
#### Tiny RDM
一个现代化轻量级的跨平台Redis桌面客户端
 [https://github.com/tiny-craft/tiny-rdm](https://github.com/tiny-craft/tiny-rdm)

{/card-describe}

文章内容 重复

![image](https://github.com/user-attachments/assets/174b13a3-2387-4e58-ad61-0617f315bd0a)

**Comment by HelloWuJiaYi** [comment]
已修复，可下载 1.4.1 版本查看。
